#!/usr/bin/env sh
# cmd/store/remove - remove a saved store
# Usage: idiot store remove <name>

. "$(dirname "$0")/../../lib/common.sh"

name="${1:-}"

if [ -z "$name" ]; then
    die "usage: idiot store remove <name>"
fi

mkdir -p "$IDIOT_STORES_DIR"
store_file="$IDIOT_STORES_DIR/$name"

if [ ! -f "$store_file" ]; then
    die "store '$name' not found"
fi

rm "$store_file"
say "Removed store '$name'"
