#!/usr/bin/env sh
# cmd/store/unset - unset UBUNTU_STORE_ID
# Usage: idiot store unset
# Outputs: eval-able unset statement

. "$(dirname "${0}")/../../lib/common.sh"

main() {
    printf 'unset UBUNTU_STORE_ID\n'
}
main "$@"
