#!/usr/bin/env sh
# cmd/store/unset - unset UBUNTU_STORE_ID
# Usage: idiot store unset
# Outputs: eval-able unset statement

. "$(dirname "${0}")/../../share/common.sh"

main() {
	case "${1:-}" in
	-h | --help | help)
		help_heading "Usage:" "idiot store unset"
		exit 0
		;;
	esac
	emit_unset UBUNTU_STORE_ID
}
main "$@"
