#!/usr/bin/env sh
# cmd/vm/help - usage for the vm subcommand group

. "$(dirname "${0}")/../../lib/common.sh"

main() {
    help_heading "Usage:" "idiot vm <subcommand>"
    echo >&2
    help_heading "Subcommands:"
    help_command "run" "Launch a QEMU VM"
    help_command "ssh" "SSH into the running VM"
    help_command "scp" "Copy files to/from the running VM"
}
main "$@"
