#!/usr/bin/env sh
# cmd/arch/status - show the current target architecture
# Usage: idiot arch status

. "$(dirname "${0}")/../../share/common.sh"
include arch.sh

main() {
	case "${1:-}" in
	-h | --help | help)
		help_heading "Usage:" "idiot arch status"
		exit 0
		;;
	esac
	[ -n "${UBUNTU_STORE_ARCH:-}" ] && {
		say "${BOLD}${UBUNTU_STORE_ARCH}${RESET}"
		exit 0
	}

	say "${DIM}$(uname_to_snap_arch)${RESET}"
}
main "$@"
