#!/usr/bin/env sh
# cmd/arch/unset - unset the target architecture
# Usage: idiot arch unset
# Outputs: eval-able unset statement

. "$(dirname "${0}")/../../lib/common.sh"

printf 'unset UBUNTU_STORE_ARCH\n'
