#!/usr/bin/env sh
# cmd/todo/help - show help for the todo command group

. "$(dirname "${0}")/../../lib/common.sh"

help_heading "Usage:" "idiot todo <subcommand>"
echo >&2
help_heading "Subcommands:"
help_command "new"    "Create a new to-do list (optionally from a template)"
help_command "list"   "List saved to-do lists"
help_command "show"   "Display a to-do list"
help_command "add"    "Append an item to a list"
help_command "done"   "Mark an item as complete"
help_command "remove" "Delete a to-do list"
echo >&2
help_heading "Environment:"
help_env "IDIOT_TODO_DIR" "To-do lists directory (default: ~/.local/share/idiot/todo)"
