#!/usr/bin/env sh
# cmd/auth/export - print a credential file to stdout or write to a file
# Usage: idiot auth export [<name>] [-f|--file <file>]

. "$(dirname "${0}")/../../share/common.sh"
# shellcheck source=share/creds.sh
. "$(dirname "${0}")/../../share/creds.sh"
# shellcheck source=share/fzf.sh
. "$(dirname "${0}")/../../share/fzf.sh"

main() {
	name=""
	outfile=""

	while [ $# -gt 0 ]; do
		case "${1}" in
		-h | --help | help)
			help_heading "Usage:" "idiot auth export [<name>] [-f <file>]"
			echo >&2
			help_heading "Options:"
			help_option "-f, --file <file>" "Write to file instead of stdout"
			exit 0
			;;
		-f | --file)
			[ -n "${2:-}" ] || die "option '${1}' requires an argument"
			outfile="${2}"
			shift 2
			;;
		-*)
			die "unknown option: ${1}"
			;;
		*)
			[ -n "${name}" ] && die "usage: idiot auth export [<name>] [-f <file>]"
			name="${1}"
			shift
			;;
		esac
	done

	[ -n "${name}" ] || {
		name=$(fzf_pick_from_dir \
			"${IDIOT_AUTH_DIR}" \
			"export auth> " \
			"no credentials found") || exit 0
	}

	require_cred "${name}"
	cred_file="${IDIOT_AUTH_DIR}/${name}"

	if [ -n "${outfile}" ]; then
		cp "${cred_file}" "${outfile}"
		say "Exported '${BOLD}${name}${RESET}' to '${BOLD}${outfile}${RESET}'"
	else
		cat "${cred_file}"
	fi
}

main "$@"
