#!/usr/bin/env sh
# cmd/inspect/snap - print snap/snapcraft.yaml or meta/snap.yaml from a snap file

. "$(dirname "${0}")/../../share/common.sh"

main() {
	case "${1:-}" in
	-h | --help | help)
		help_heading "Usage:" "idiot inspect snap <snap-file>"
		exit 0
		;;
	esac

	[ $# -ge 1 ] || die "usage: idiot inspect snap <snap-file>"

	snap_file="${1}"

	[ -f "${snap_file}" ] ||
		die "file not found: ${snap_file}"

	require unsquashfs

	! unsquashfs -q -cat "${snap_file}" snap/snapcraft.yaml >&2 2>/dev/null ||
		exit 0

	unsquashfs -q -cat "${snap_file}" meta/snap.yaml >&2 2>/dev/null ||
		die "neither snap/snapcraft.yaml nor meta/snap.yaml found in ${snap_file}"
}
main "$@"
