#!/usr/bin/env sh
# cmd/model/list - list configured model repos

. "$(dirname "${0}")/../../share/common.sh"
include models.sh

main() {
	case "${1:-}" in
	-h | --help | help)
		help_heading "Usage:" "idiot model list"
		exit 0
		;;
	esac

	help_heading "Built-in:"
	model_list_section "${IDIOT_DATA_DIR}/models"
	echo >&2
	help_heading "User:"
	model_list_section "${IDIOT_MODEL_REPOS_DIR}"
}
main "$@"
