#!/usr/bin/env sh
# cmd/model/update - clone or pull the canonical/models repository
# Usage: idiot model update

. "$(dirname "${0}")/../../share/common.sh"
# shellcheck source=share/models.sh
. "$(dirname "${0}")/../../share/models.sh"

main() {
	case "${1:-}" in
	-h | --help | help)
		help_heading "Usage:" "idiot model update"
		exit 0
		;;
	esac
	MODELS_REPO_URL="https://github.com/canonical/models.git"

	if [ -d "${IDIOT_MODELS_DIR}/.git" ]; then
		say "Updating models repository..."
		git -C "${IDIOT_MODELS_DIR}" pull >&2
	else
		say "Cloning models repository..."
		git clone "${MODELS_REPO_URL}" "${IDIOT_MODELS_DIR}" >&2
	fi
}
main "$@"
