#!/usr/bin/env sh
# cmd/clean/help - usage for the clean subcommand group

. "$(dirname "${0}")/../../lib/common.sh"

main() {
	help_heading "Usage:" "idiot clean <subcommand>"
	echo >&2
	help_heading "Subcommands:"
	help_command "all" "Remove all snapcraft build containers and unasserted snaps"
	help_command "containers" "Remove all snapcraft build containers"
	help_command "snaps" "Remove all unasserted snaps"
}
main "$@"
